# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-26 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliyun_Ram_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_user_name', models.CharField(max_length=128, null=True, verbose_name='RAM用户名')),
                ('ram_display_name', models.CharField(max_length=128, null=True, verbose_name='RAM用户显示名称')),
                ('ram_user_accesskey', models.CharField(max_length=128, null=True, verbose_name='RAM用户key')),
                ('ram_auth', models.TextField(max_length=2048, null=True, verbose_name='RAM用户权限列表')),
                ('ram_phone', models.CharField(max_length=128, null=True, verbose_name='RAM用户手机号')),
                ('ram_mail', models.CharField(max_length=128, null=True, verbose_name='RAM用户邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Aliyun_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=128, null=True, verbose_name='阿里云用户名称')),
                ('AccessKeyID', models.TextField(max_length=128, null=True, verbose_name='阿里云用户key')),
                ('AccessKeySecret', models.TextField(max_length=128, null=True, verbose_name='阿里云用户秘钥')),
            ],
        ),
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='aliyun_ram_user',
            name='aliyun_user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ram_control.Aliyun_User', verbose_name='阿里云用户名称'),
        ),
    ]
