# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-04 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyun_ram_user',
            name='ram_comment',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
    ]
