# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('host_manager', '0002_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='用户拥有的角色'),
        ),
    ]
