# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manager', '0003_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='level',
            field=models.CharField(default=2, max_length=32, verbose_name='服务级别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessunit',
            name='owner',
            field=models.CharField(default=2, max_length=32, verbose_name='负责人'),
            preserve_default=False,
        ),
    ]
