# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_manager', '0004_auto_20190321_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=32, verbose_name='产品名称'),
        ),
    ]
